# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 689a8ce9290b6e164756b2e2f50883e1feb3b253255c6b395778f2c37a2ad295688e2c2137f817c74eff337e58dd06151c1ae36a5bbc3a73f21792d5e497dd16

test:
  secret_key_base: 65bd97046b9a998c482477429c5cf6af9dd1bfc5a99aca2095449cd9b727eaedc01a9b5166f2e695c513ceb8ced94d81e2ffc2ad0887168c8d12b8811fe88605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
